#!/bin/sh

if grep -q 'VERSION="8 (jessie)"' /etc/os-release; then
    distro=jessie
elif grep -q 'VERSION="9 (stretch)"' /etc/os-release; then
    distro=stretch
else
    exit 0
fi

deb_archive=http://archive.kernel.org/debian-archive
deb_archive_security=http://archive.kernel.org/debian-archive/debian-security
sed -ri "s;^(\s*deb\s+http://(httpredir|deb).debian.org/debian\s+$distro-updates\b.*);#\1;" /etc/apt/sources.list
sed -ri "s;^(\s*deb\s+)http://(httpredir|deb).debian.org;\1$deb_archive;" /etc/apt/sources.list
sed -ri "s;^(\s*deb\s+)http://security.debian.org/debian-security;\1$deb_archive_security;" /etc/apt/sources.list
sed -ri "s;^(\s*deb\s+)http://security.debian.org;\1$deb_archive_security;" /etc/apt/sources.list

tmp="$(mktemp)"
DEBIAN_FRONTEND=noninteractive apt-get update -q 2>"$tmp"
if grep -qE ' KEYEXPIRED [0-9]' "$tmp"; then
    printf 'APT::Get::AllowUnauthenticated "true";\n' >/etc/apt/apt.conf.d/99unauthenticated
fi
rm "$tmp"
